# Generated by Django 6.0.1 on 2026-01-26 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_comment_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, null=True),
        ),
    ]
