# Generated by Django 6.0.1 on 2026-01-26 19:25

from django.db import migrations
from django.db.models import Q
from django.utils.text import slugify


def backfill_slugs(apps, schema_editor):
    Question = apps.get_model('questions', 'Question')
    existing = set(Question.objects.exclude(slug__isnull=True).exclude(slug='').values_list('slug', flat=True))
    for question in Question.objects.filter(Q(slug__isnull=True) | Q(slug='')).order_by('id'):
        base_slug = slugify(question.title) or "question"
        slug = base_slug
        counter = 1
        while slug in existing:
            counter += 1
            slug = f"{base_slug}-{counter}"
        question.slug = slug
        question.save(update_fields=['slug'])
        existing.add(slug)


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_question_slug'),
    ]

    operations = [
        migrations.RunPython(backfill_slugs, noop),
    ]
