# Generated by Django 6.0.1 on 2026-01-27 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0006_question_slug_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='link',
            field=models.URLField(blank=True),
        ),
    ]
